services:
  mysql:
    image: mysql
    ports:
      - "3307:3306" # Mapeia a porta 3307 do host para a porta 3306 do container
    expose:
      - "3306" # A porta interna do container continua 3306
    environment:
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=123
      - MYSQL_DATABASE=mydb
      - MYSQL_ROOT_PASSWORD=123
